data = {
    Easy:[
        "Brush",
        "Cactus",
        "Enter The Nether",
        "Tame a Wolf",
        "Build a Snow Golem",
        "Trade with a Villager",
        "Loot a Desert Temple",
        "Loot a Dungeon",
        "Loot an Igloo",
        "Block an Arrow",
        "Golden Apple",
        "9 Golden Carrot",
        "Turn Husk into Drowned",
        "Sleep in a bed",
        "18 Smooth Stone",
        "Blast Furnace",
        "Crossbow",
        "Cake",
        "Flint & Steel",
        "Shears",
        "13 Feathers",
        "Lava Bucket",
        "22 Leather",
        "Shield",
        "Full Iron Armor",
        "53 Wool",
        "19 Copper Blocks",
        "Gold Block",
        "31 Dead Bushes",
        "53 Glow Lichen",
        "14 Emeralds",
        "18 Spider Eyes",
        "12 Gun Powder",
        "Bucket of Axolotl",
        "Get Dolphin's Grace",
        "Kill an Enderman",
        "Fire a Crossbow with Firework",
        "Ring a Bell",
        "Break a Monster Spawner",
        "Slime Ball",
        "Armor Stand",
        "Dispenser Block",
        "Crafter Block",
        "Target Block",
        "19 Tripwire Hooks",
        "17 Books",
        "10 Bookshelves",
        "Kill a Phantom",
        "Amethyst Shard",
        "2 Cauldrons",
        "4 Chiseled Bookshelves",
        "2 Lecterns",
        "7 Note Blocks",
        "23 Paintings",
        "8 Item Frames",
        "6 Glowing Item Frames",
        "30 Scaffolding",
        "7 Cocoa Beans",
        "10 Bamboo Blocks",
        "32 Composters",
        "4 Blast Furnaces",
        "10 Looms",
        "16 Cherry Saplings",
        "Drink Mushroom Stew",
        "Drink Milk",
        "8 Pumpkin Pies",
        "14 Dried Kelp Blocks",
        "31 Smooth Stone",
        "Nautilus Shell",
        "Any Pottery Sherd",
        "Any Armor with Armor Trim",
        "5 Cobwebs",
        "Iron Sword",
        "Golden Shovel",
        "Iron Hoe"
    ],
    Normal:[
        "Spyglass",
        "Ride and Jump with a Camel",
        "2 Name Tags",
        "8 Emerald Blocks",
        "14 Sea Lanterns",
        "Anvil",
        "16 Copper Bulbs",
        "13 Enderpearls",
        "Bucket of Pufferfish",
        "Heart of the Sea",
        "Honey Block",
        "Diamond",
        "Saddle",
        "Diamond Pickaxe",
        "Make an Iron Golem",
        "Finish a Raid",
        "Build a Herobrine Shrine",
        "Clear a Trial Chamber",
        "Cure a Zombie Villager",
        "Play Any Music Disc",
        "Blow up 10 TNT in 1 Blast.",
        "6 Blaze Rods",
        "Lodestone",
        "Fill up a Respawn Anchor",
        "Achieve Return to Sender Advancement",
        "Shear a Mooshroom",
        "Kill a Blaze in the Overworld",
        "Reach the Nether Roof",
        "Buld an Iron Golem",
        "Tame a Cat",
        "Give a Armor to a Wolf",
        "Use Soulspeed III",
        "Kill a Piglin Brute",
        "Fire a Multishot Crossbow",
        "Use a Goat Horn",
        "Use an Enchantment Table",
        "4 Slime Blocks",
        "10 Wind Charges",
        "Kill a Zoglin",
        "8 Glowstone",
        "5 Redstone Lamps",
        "3 Observers",
        "4 Breeze Rods",
        "10 Tinted Glass",
        "9 Crying Obsidian",
        "Brew a Potion",
        "2 Beehives",
        "Jukebox",
        "48 Soul Torches",
        "13 Soul Campfires",
        "24 Soul Lanterns",
        "Drink Rabbit Stew",
        "32 Cookies",
        "48 Terracotta",
        "Ghast Tear",
        "Sniffer Egg",
        "Turtle Egg",
        "Torchflower",
        "Pitcher Plant",
        "Trade with a Master Villager",
        "Tame a Parrot",
        "Get Any Type of Froglight",
        "Ride a Horse with a Saddle",
        "Kill 4 Guardians",
        "Kill 6 Wither Skeletons",
        "Ancient Debris",
        "22 Obsidian",
        "Diamond Chestplate",
        "Duplicate a Smithing Template",
        "Any Horse Armor",
        "Use Silktouch",
        "Use Any Banner Pattern",
        "Light a Candle on a Cake",
        "54 Lapis Lazuli",
        "Ride a Strider"
    ],
    Hard:[
        "Recovery Compass",
        "Full Diamond Armor with Any Enchants",
        "Full Set of Armor with Armor Trim",
        "4 Blocks of Diamond",
        "Block of Netherite",
        "15 Blocks of Iron",
        "22 Blocks of Gold",
        "31 Blocks of Coal",
        "64 Blocks of Emerald",
        "59 Blocks of Redstone",
        "54 Blocks of Lapis Lazuli",
        "Enchanted Golden Apple",
        "Reach Level 30",
        "Mace",
        "Trident",
        "Conduit",
        "Dragon Egg",
        "Elytra",
        "Dragon Head",
        "Beacon",
        "Shulker Box",
        "Break a Diamond Hoe",
        "Respawn the Enderdragon",
        "Turtle Helmet",
        "Kill 3 Elder Guardians",
        "Kill a Warden",
        "Kill a Ravager",
        "Kill an Evoker",
        "Dragon's Breath",
        "Have All Potion Effects at Once",
        "Give a Villager a Piece of Netherite Armor",
        "Setup a Level 30 Enchantment Table",
        "Totem of Undying",
        "Ride a Skeleton Horse",
        "Obtain All Froglights",
        "Eat Chorus Fruit",
        "Have Full Armor with Mending",
        "Obtain 2 of the Uncraftable Banner Patterns",
        "Max Enchant a Netherite Pickaxe",
        "Pigstep Music Disc",
        "Creator Music Disc",
        "Precipice Music Disc",
        "Relic Music Disc",
        "otherside Music Disc",
        "\"5\" Music Disc",
        "Use Swift Sneak",
        "Enter a Woodland Mansion",
        "Obtain Hero of the Village V Effect",
        "Ominous Trial Key",
        "Obtain 9 Different Kinds of Armor Trim Templates"
    ],
    Insane:[
        "Fully Power a Beacon",
        "Obtain All Mob Heads",
        "Achieve How Did We Get Here Advancement",
        "Tame All Dog and Cat Breeds",
        "Obtain Every Music Disc",
        "Brew Every Possible Potion",
        "Achieve Adventure Time Advancement",
        "Kill The Enderdragon 20 Times",
        "Obtain All Armor Trim Templates",
        "Achieve Monsters Hunted Advancement",
        "Reach The Farlands",
        "Obtain All Goat Horns"
    ]
}