data = {
    Easy:[
        "Brush",
        "Cactus",
        "Enter The Nether",
        "Tame a Wolf",
        "Make a Snow Golem",
        "Trade with a Villager",
        "Loot a Desert Temple",
        "Loot a Dungeon",
        "Loot an Igloo",
        "Block an Arrow",
        "Golden Apple",
        "9 Golden Carrot",
        "Turn Husk into Drowned",
        "Sleep in a bed",
        "12 Leather",
        "18 Smooth Stone",
        "Blast Furnace",
        "Crossbow"
    ],
    Normal:[
        "Bucket of Pufferfish",
        "Heart of the Sea",
        "Recovery Compass",
        "Honey Block",
        "Diamond",
        "Break 10 Obsidian",
        "Amethyst Shard",
        "Make an Iron Golem",
        "Win a Raid",
        "Build a Herobrine Shrine",
        "Clear a Trial Chamber",
        "Cure a Zombie Villager",
        "Play Any Music Disc",
        "Blow up 10 TNT in 1 Blast.",
        "6 Blaze Rods",
        "Lodestone",
        "Fill up a Respawn Anchor",
        "Achieve Return to Sender Advancement",
        "Shear a Mooshroom",
        "Kill a Blaze in the Overworld",
        "Reach the Nether Roof"
    ],
    Hard:[
        "4 Diamond Blocks",
        "Netherite Block",
        "Enchanted Golden Apple",
        "Reach Level 30",
        "Mace",
        "Trident",
        "Conduit",
        "Dragon Egg",
        "Elytra",
        "Dragon Head",
        "Beacon",
        "Shulker Box",
        "Break a Diamond Hoe",
        "Respawn the Enderdragon",
        "Turtle Helmet",
        "Kill 3 Elder Guardians",
        "Kill a Warden",
        "Dragon's Breath",
        "Have All Potion Effects at Once",
        "Give a Villager a Full Set of Netherite",
    ],
    Insane:[
        "Fully Power a Beacon",
        "Obtain All Mob Heads",
        "Achieve How Did We Get Here Advancement",
        "Tame All Dog and Cat Breeds",
        "Obtain Every Music Disc",
        "Brew Every Possible Potion",
        "Achieve Adventure Time Advancement",
        "Kill The Enderdragon 20 Times",
        "Obtain All Armor Trims",
        "Achieve Monsters Hunted Advancement",
        "Reach The Farlands"
    ]
}